### ISSUE TITLE
可以给一个详细一点的例子吗？

### ISSUE THREAD

**Issue by wangshunping** [iresty/lua-resty-test#2]
现在写的lua+nginx代码需要测试，但是并不明白如何使用或者更好的使用。

当然，我是看了
https://moonbingbing.gitbooks.io/openresty-best-practices/content/test/unittest.html。
还是不明白。

可以以4.7提供的例子来说明，该如何测试吗？

**Comment by membphis** [comment]
好的，稍候我们补充一下使用用例

**Comment by fankeke** [comment]
确实看不懂啊，希望详细科普下，到底测试了些啥东东～～～

**Comment by ozzy-ext** [comment]
Ну, молодцы, вообще. Возможно, тут было решение мой проблемы ((

**Comment by membphis** [comment]
> Ну, молодцы, вообще. Возможно, тут было решение мой проблемы ((

can you translate it to English?

**Comment by membphis** [comment]
already added ^_^
