### ISSUE TITLE
about bench_run（）

### ISSUE THREAD

**Issue by zhaoxihe** [iresty/lua-resty-test#6]
Why does bench_run() always appear "the micro test must be comsume within 2sec" and cannot be unlocked properly? Annotation of ngx. flush () in run () will allow normal testing. Why?Or is my use incorrect?

**Comment by membphis** [comment]
I am going to give up this project and suggest that you try other way, such as `wrk`.

**Comment by membphis** [comment]
will focus on single test case later.
